### ISSUE TITLE
Link previews count towards click count

### ISSUE THREAD

**Issue by stophecom** [onderonur/onurl#9]
First of all, great project!

I was wondering if there is a way to prevent crawler visits (or other services, robots) to count towards the `click` count. 

Here is an example:
I create a link and share it via Slack. Slack will fetch the link to create a rich preview of the destination - this visit will count as a `click`. 

How would you prevent that click count? The only way I see is to filter for some `User-agent` - but before I do so, I'd be happy to hear your opinion.

Thanks in advance.

**Comment by onderonur** [comment]
Hi!

First of all, thanks for your interest in this project and the question as well.
I didn't think about this situation actually, but using some sort of a filter right before increasing the count is a great idea.
And I guess you can even find some npm package that can find out if your site is visited by an actual user or a crawler etc.
Using `User-agent` header is also a fine idea I guess.

If you find a solution to this, I would gladly want to know your solution. Marked this issue as a question and closing it for now.

Thanks again!

**Comment by stophecom** [comment]
Thanks for the reply. I actually found https://github.com/monperrus/crawler-user-agents - and I'm using it to block known crawlers. Works fine in my case, thanks!
